### ISSUE TITLE
what is the meaning of attention_size?

### ISSUE THREAD

**Issue by Cumberbatch08** [ilivans/tf-rnn-attention#14]
In attention part, the attention_size is a Hyperparameter, when we calculate the alpha, the shape of alpha is not about of attention_size. So, the attention_size is to do what?
![image](https://user-images.githubusercontent.com/30173360/48460701-3a961a00-e80b-11e8-91fd-db2ffb24d8b0.png)

**Comment by ilivans** [comment]
Attention size is an inner size of attention layer, `alphas` are just probabilities of tokens. Attention size allows to regulate 'capacity' of attention layer.

**Comment by Cumberbatch08** [comment]
Thanks, does attention_size have any physical meaning? How to set this size?

**Comment by ilivans** [comment]
It's a linear size of layer weights similar to size of fully-connected layer or hidden size of RNN. The value should be chosen accordingly by means of grid search or something like that.

**Comment by Cumberbatch08** [comment]
Thanks a lot. u_omgea represents context vector, so I think the attention_size should be set as hidden_size * 2.
