### ISSUE TITLE
Is there any code for visualizing attention picture

### ISSUE THREAD

**Issue by xingyuanbu** [ilivans/tf-rnn-attention#4]
Thanks for your code about training a attention model~
But I didn't find a visualizing code which can product the picture in your README.md

Is it possible to share the code by which we can visualize the attention weight?

**Comment by ilivans** [comment]
I'm sorry, I really made this picture's origin not clear. Actually, one can find how to create such visualization from https://github.com/ilivans/attention-sentiment/blob/master/code/testing_reviews.ipynb. However, there are a lot of excess things and you are not the first who ask me such question, so I think I will make some simple code example shortly.

**Comment by ilivans** [comment]
Done
