### ISSUE TITLE
About padding sentences

### ISSUE THREAD

**Issue by theanhle** [ilivans/tf-rnn-attention#5]
Hi Ilivans,

In your implementation, you padded all training set to a fixed length: 250
+ X_train = zero_pad(X_train, SEQUENCE_LENGTH)
+ batch_ph = tf.placeholder(tf.int32, [None, SEQUENCE_LENGTH])
But I want to calculate this factor for each mini-batch, that's why I have to declare batch_ph of shape [None, None]. So in the attention.py file: sequence_length = inputs_shape[1].value will be "None" then the error will be appear in the command: exps = tf.reshape(tf.exp(vu), [-1, sequence_length]):
"Failed to convert object of type <class 'list'> to Tensor. Contents: [-1, None]. Consider casting elements to a supported type."
Do you have any idea for this problem?
Thank you in advance!

**Comment by ilivans** [comment]
Hi Le The Anh,

Actually, I don't know when it's necessary to make variable maximum sequence length. 
Nevertheless, it seems I have managed to solve your problem. The solution is to use `tf.Tensor` object as a `shape` argument for `tf.reshape`.
Changes are already in master.

Let me know if there are any questions left.
